pool:
  vmImage: 'ubuntu-20.04'

trigger:
  - stable
  - develop

steps:
  - task: NodeTool@0
    displayName: 'Use Node 15.x'
    inputs:
      versionSpec: 15.x

  - script: 'yarn install --frozen-lockfile --silent'
    displayName: 'Install local dependencies'

  - script: |
      echo "
      NodeJS: $(node --version)
      NPM: v$(npm --version)
      Yarn: v$(yarn --version)
      "
    displayName: 'Show tools versions'

  - script: 'yarn run format:check'
    displayName: 'Check code format'

  - script: 'yarn run lint:lib'
    displayName: 'Lint library'

  - script: 'yarn run lint:demo'
    displayName: 'Lint demo'

  - script: 'yarn run lint:demo-e2e'
    displayName: 'Lint demo e2e'

  - script: 'yarn run build:lib'
    displayName: 'Build library'

  - script: 'yarn run build:demo --progress=false'
    displayName: 'Build demo'

  - script: 'yarn run test --ci --coverage'
    displayName: 'Run unit tests'
