version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:15-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/ng-in-viewport

anchor_1: &defaults
  executor: node

anchor_2: &restore_cache_defaults
  keys:
    - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
    - ng-in-viewport-

general:
  branches:
    only:
      - develop

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: |
          git --version
          node --version
          yarn --version
      - run: yarn install --frozen-lockfile --silent
      - run: |
          yarn run build:lib
          yarn run build:demo --progress=false
      - save_cache:
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  code_format:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: 'yarn run format:check'

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: |
          yarn run lint:lib
          yarn run lint:demo
          yarn run lint:demo-e2e

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: |
          yarn run test --ci --coverage
          mkdir ./tmp
          cp ./coverage/all/lcov.info ./tmp/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - lcov.info

  upload_coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - attach_workspace:
          at: ~/ng-in-viewport/tmp
      - run:
          name: Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run: yarn run codecov --file ./tmp/lcov.info
      - run: ./tmp/cc-test-reporter format-coverage -t lcov -o ./tmp/codeclimate.json ./tmp/lcov.info
      - run: ./tmp/cc-test-reporter upload-coverage -i ./tmp/codeclimate.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_format:
          requires:
            - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - upload_coverage:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - stable
                - develop
