kind: pipeline
name: default

steps:
  - name: Build and test
    image: node:15
    commands:
      - 'yarn install --frozen-lockfile --silent'
      - 'yarn run lint:lib'
      - 'yarn run lint:demo'
      - 'yarn run lint:demo-e2e'
      - 'yarn run build:lib'
      - 'yarn run build:demo --progress=false'
      - 'yarn run test --ci --coverage'
